// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA1xme2OBtcrpOMjP2ywFnonGvP5kbMuY',
    appId: '1:60887274029:web:ee1766381215a3221a9ea4',
    messagingSenderId: '60887274029',
    projectId: 'auth-module-e2090',
    authDomain: 'auth-module-e2090.firebaseapp.com',
    storageBucket: 'auth-module-e2090.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH86kqTd_Rppw4GcbPlqv1CBB_XZ09x9c',
    appId: '1:60887274029:android:fc80fe6c4ef8c9041a9ea4',
    messagingSenderId: '60887274029',
    projectId: 'auth-module-e2090',
    storageBucket: 'auth-module-e2090.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-uR_trcOtu75rNDC1u4GMFwdZMOt1V6o',
    appId: '1:60887274029:ios:6829c2332299871b1a9ea4',
    messagingSenderId: '60887274029',
    projectId: 'auth-module-e2090',
    storageBucket: 'auth-module-e2090.firebasestorage.app',
    iosBundleId: 'com.example.authModule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-uR_trcOtu75rNDC1u4GMFwdZMOt1V6o',
    appId: '1:60887274029:ios:6829c2332299871b1a9ea4',
    messagingSenderId: '60887274029',
    projectId: 'auth-module-e2090',
    storageBucket: 'auth-module-e2090.firebasestorage.app',
    iosBundleId: 'com.example.authModule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA1xme2OBtcrpOMjP2ywFnonGvP5kbMuY',
    appId: '1:60887274029:web:8cc44073023c7cfe1a9ea4',
    messagingSenderId: '60887274029',
    projectId: 'auth-module-e2090',
    authDomain: 'auth-module-e2090.firebaseapp.com',
    storageBucket: 'auth-module-e2090.firebasestorage.app',
  );
}
