// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBML5i5xsMJDN3P4fmgoWtCRJK7MdcYAY4',
    appId: '1:739690866225:web:ce90d01dce37de0bb79710',
    messagingSenderId: '739690866225',
    projectId: 'cooklog-70e45',
    authDomain: 'cooklog-70e45.firebaseapp.com',
    storageBucket: 'cooklog-70e45.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0-wcwhP1ark37YNEChgpw0tkW6E8JDdo',
    appId: '1:739690866225:android:8571fc7f97d0a435b79710',
    messagingSenderId: '739690866225',
    projectId: 'cooklog-70e45',
    storageBucket: 'cooklog-70e45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmffpU3P1hsPgUayyXceqkpFQX46BUL9I',
    appId: '1:739690866225:ios:0bf1cb37a6c237eeb79710',
    messagingSenderId: '739690866225',
    projectId: 'cooklog-70e45',
    storageBucket: 'cooklog-70e45.firebasestorage.app',
    iosBundleId: 'com.example.cooklog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmffpU3P1hsPgUayyXceqkpFQX46BUL9I',
    appId: '1:739690866225:ios:0bf1cb37a6c237eeb79710',
    messagingSenderId: '739690866225',
    projectId: 'cooklog-70e45',
    storageBucket: 'cooklog-70e45.firebasestorage.app',
    iosBundleId: 'com.example.cooklog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBML5i5xsMJDN3P4fmgoWtCRJK7MdcYAY4',
    appId: '1:739690866225:web:85f8bf09400504dfb79710',
    messagingSenderId: '739690866225',
    projectId: 'cooklog-70e45',
    authDomain: 'cooklog-70e45.firebaseapp.com',
    storageBucket: 'cooklog-70e45.firebasestorage.app',
  );

}