// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmOJgFqih-J5g97kSomBb72tRzg6gGXIo',
    appId: '1:243589442671:web:2f70c5ebbe6f824671b19a',
    messagingSenderId: '243589442671',
    projectId: 'fir-crud-basics-4ad15',
    authDomain: 'fir-crud-basics-4ad15.firebaseapp.com',
    storageBucket: 'fir-crud-basics-4ad15.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbsOhQzlb-5kP6aSxuQRk_ioQKpzvD_Vs',
    appId: '1:243589442671:android:df266719eacd264b71b19a',
    messagingSenderId: '243589442671',
    projectId: 'fir-crud-basics-4ad15',
    storageBucket: 'fir-crud-basics-4ad15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7gs-Yvp73SSRVmA_EiriL7rUFcYOR8Ns',
    appId: '1:243589442671:ios:bc05af388ec397ce71b19a',
    messagingSenderId: '243589442671',
    projectId: 'fir-crud-basics-4ad15',
    storageBucket: 'fir-crud-basics-4ad15.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7gs-Yvp73SSRVmA_EiriL7rUFcYOR8Ns',
    appId: '1:243589442671:ios:bc05af388ec397ce71b19a',
    messagingSenderId: '243589442671',
    projectId: 'fir-crud-basics-4ad15',
    storageBucket: 'fir-crud-basics-4ad15.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmOJgFqih-J5g97kSomBb72tRzg6gGXIo',
    appId: '1:243589442671:web:fdc5a070ff73469371b19a',
    messagingSenderId: '243589442671',
    projectId: 'fir-crud-basics-4ad15',
    authDomain: 'fir-crud-basics-4ad15.firebaseapp.com',
    storageBucket: 'fir-crud-basics-4ad15.firebasestorage.app',
  );
}
